export const COLOR_BG = '#121212'
export const COLOR_DARK = '#0e0e0e'
export const COLOR_PRIMARY = '#BB86FC'
export const COLOR_PRIMARY_VARIANT = '#3700b3'
export const COLOR_ACCENT = '#03dac6'
export const COLOR_ERROR = '#CF6679'
export const COLOR_TEXT = 'white'
export const MOBILE_WIDTH = '800px'